name: read_quest
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  connectivity_plus: ^6.1.4
  email_validator: ^3.0.0
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_native_splash: ^2.4.4
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.1.0
  gap: ^3.0.1
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  http: ^1.4.0
  image_picker: ^1.1.2
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  syncfusion_flutter_pdfviewer: ^24.1.41
  web_socket_channel: ^3.0.3

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - flutter_native_splash.yaml
    - .env
